### ISSUE TITLE
newbie installing pylint for sublimelinter

### ISSUE THREAD

**Issue by Gittim89531** [SublimeLinter/SublimeLinter-pylint#12]
**Summary**  
Trying to install **pylint** for **Sublimelinter**.
I have tried to set the `PATH` correctly within Sublimelinter.
But I keep getting errors.  
I had posted this to Sublimelinter google groups and I was redirected here for possible help.

Can you help me set things right?

Although I have Python 2.7 installed (it comes standard with my mac) I want to program only in Python 3.4.  I need to keep Python 2.7 only because some other programs need it.

**Details**  

SublimeLinter version:   3.4.13
Linter executable (e.g. jshint): pylint
Linter executable version (e.g. v2.4.1): 
pylint 1.3.0, 
astroid 1.2.0, common 0.62.1
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Brand new MacBook Pro  operating OS mavericks. : 
Just downloaded and installed Python3.4.  It has pip built in.
Then I installed pylint successfully using 
`pip3.4 install pylint`

I can run **pylint** successfully from the command line.

The `Path` variable seems fine.  If I type: 

```
$which pylint  
/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint  
$which python3.4  
/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4  

```

My **.bash_profile** (I know this may be irrelevant, since Sublimelinter won't look here, I think) contains the following lines (including the parent directory of the pylint executable) which were automatically added by the Python3.4 installer

```
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH
```

When I try to install **pylint** package for use with sublimelinter the console reports a failure to install.  See below for pasted results.

Here is my **sublimelinter settings** with the **paths** pointing (I hope) correctly

```
"paths": {
            "linux": [],
            "osx": [
                "/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [
                "/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4"
            ],
            "windows": []

```

Here is the output from **Sublimelinter console when I start up Sublime text**:

```

startup time: 0.265025
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/cn/1_813xc936j4zmwhpgp_t2840000gn/T/SublimeLinter3 
Writing file /Users/tim/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings with encoding UTF-8 (atomic)
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
loaded 837 snippets
reloading Packages/User/SublimeLinter.sublime-settings
found 5 files for base name Main.sublime-menu
Package Control: Skipping automatic upgrade, last run at 2014-08-12 09:58:00, next run at 2014-08-12 10:58:00 or after


```

Here is the output from console (Sublime linter in Debug mode) when I try to **install pylint package using the Package Control**:

```
ignored packages updated to: [Vintage, SublimeLinter-pylint]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading plugin SublimeLinter-pylint.linter
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 3} 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint
/Library/Frameworks/Python.framework/Versions/3.4/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/bin
/Users/tim/bin

SublimeLinter: find_posix_python: python3 => /Library/Frameworks/Python.framework/Versions/3.4/bin/python3 
SublimeLinter: find_python: system python = /Library/Frameworks/Python.framework/Versions/3.4/bin/python3 
SublimeLinter: find_python: available version = {'minor': 4, 'major': 3} 
SublimeLinter: find_python: <= ('/Library/Frameworks/Python.framework/Versions/3.4/bin/python3', None, 3, 4) 
SublimeLinter: sys.path for /Library/Frameworks/Python.framework/Versions/3.4/bin/python3:
/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages

SublimeLinter: pylint linter reloaded 
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /usr/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pylint' path = /Library/Frameworks/Python.framework/Versions/3.4/bin/pylint 
SublimeLinter: find_python: <= ('/usr/bin/python', '/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint', 2, 7) 
SublimeLinter: pylint version query: /usr/bin/python /Library/Frameworks/Python.framework/Versions/3.4/bin/pylint --version 
SublimeLinter: WARNING: no pylint version could be extracted from:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pylint==1.3.0



```

**Comment by jeremejevs** [comment]
Is there any progress? `find_python` is still pretty bad at picking the right Python. I don't see any related issues in the original project.

**Comment by vikbez** [comment]
:+1:  same issue

**Comment by utkonos** [comment]
This problem also appears when using pydocstyle linter:
https://github.com/SublimeLinter/SublimeLinter-pydocstyle/issues/12

**Comment by dfduarte** [comment]
Hello guys, good morning?

Any lucky fixing this issue? I'm facing a very similar problem here in MacOS Sierra using Python 3.6.

```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/dduarte/Library/Application Support/Sublime Text 3/Packages
state path: /Users/dduarte/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/dduarte/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.182781
using gpu buffer for window
first paint time: 0.244819
startup time: 0.245935
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-pylint.linter
SublimeLinter: pylint linter loaded 
reloading plugin SublimeLinter-rubocop.linter
SublimeLinter: rubocop linter loaded 
reloading plugin SublimeLinter-shellcheck.linter
SublimeLinter: shellcheck linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/gm/s958_vvs6sx5w896tj0n2d5h0000gn/T/SublimeLinter3-dduarte 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 3} 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/local/lib/python3.6/site-packages/pylint
/Users/dduarte/.rvm/gems/ruby-2.4.0/bin
/Users/dduarte/.rvm/gems/ruby-2.4.0@global/bin
/Users/dduarte/.rvm/rubies/ruby-2.4.0/bin
/opt/local/bin
/opt/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/dduarte/.rvm/bin
 
SublimeLinter: find_posix_python: python3 => /usr/local/bin/python3 
SublimeLinter: find_python: system python = /usr/local/bin/python3 
SublimeLinter: find_python: available version = {'minor': 6, 'major': 3} 
SublimeLinter: find_python: <= ('/usr/local/bin/python3', None, 3, 6) 
SublimeLinter: sys.path for /usr/local/bin/python3:
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/site-packages
 
SublimeLinter: ENV['GEM_HOME'] = '/Users/dduarte/.rvm/gems/ruby-2.4.0' 
Package Control: Skipping automatic upgrade, last run at 2017-04-28 10:30:59, next run at 2017-04-28 11:30:59 or after
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /opt/local/bin/python 
SublimeLinter: find_python: available version = {'minor': 7, 'major': 2} 
SublimeLinter: find_python: 'pylint' path = /usr/local/bin/pylint 
SublimeLinter: find_python: <= ('/opt/local/bin/python', '/usr/local/bin/pylint', 2, 7) 
SublimeLinter: pylint version query: /opt/local/bin/python /usr/local/bin/pylint --version 
SublimeLinter: WARNING: no pylint version could be extracted from:
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 7, in <module>
    from pylint import run_pylint
ImportError: No module named pylint
 
reloading settings Packages/User/SublimeLinter.sublime-settings
```

**Comment by TomHarrop** [comment]
The only way I've been able to get this to work on Sierra is to make pylint available to system python (`/usr/bin/python`):

```
wget https://bootstrap.pypa.io/get-pip.py
sudo /usr/bin/python get-pip.py
sudo /usr/local/bin/pip install pylint
```
I'm hoping that since my `$PATH` is set to use homebrew `python` and `pip`, having the additional `pip` in `/usr/local/bin/pip` won't cause any problems:

```
$ which -a python
/usr/local/opt/python/libexec/bin/python
/usr/bin/python
$ which -a pip
/usr/local/opt/python/libexec/bin/pip
/usr/local/bin/pip
```

**Comment by braver** [comment]
SublimeLinter 4 should vastly improve virtual env setups and make it easier to install linters.
