### ISSUE TITLE
ImportError: No module named 'SublimeLinter'

### ISSUE THREAD

**Issue by tbarbugli** [SublimeLinter/SublimeLinter-pylint#19]
```
reloading plugin SublimeLinter-pylint.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in /Users/tommaso/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-pylint.sublime-package", line 14, in <module>
ImportError: No module named 'SublimeLinter'
```

**Comment by NotSqrt** [comment]
Well, did you install ``SublimeLinter`` before ``SublimeLinter-pylint`` ?

**Comment by tbarbugli** [comment]
missed that part

**Comment by NotSqrt** [comment]
No problem :+1:
