### ISSUE TITLE
Linter finds no errors and silently stops working

### ISSUE THREAD

**Issue by flipdazed** [SublimeLinter/SublimeLinter-pylint#35]
The linter silently stops working and displays no errors when it is directly called

When displaying the console the following output is received

```
Traceback (most recent call last):
  File ".\SublimeLinter.py", line 692, in run_
  File ".\SublimeLinter.py", line 721, in _run
  File ".\SublimeLinter.py", line 143, in run_once
  File ".\sublimelinter\modules\base_linter.py", line 291, in run
  File ".\sublimelinter\modules\python.py", line 264, in parse_errors
AttributeError: 'module' object has no attribute 'Redefined'
```

I found that the offending line is in 

```
            elif isinstance(error, (pyflakes.messages.RedefinedWhileUnused,
                                    pyflakes.messages.UndefinedName,
                                    pyflakes.messages.UndefinedExport,
                                    pyflakes.messages.UndefinedLocal,
                                    pyflakes.messages.Redefined,                  #### <= the offender
                                    pyflakes.messages.UnusedVariable)):
                underline_word(error.lineno, error.message, underlines)
```

Commenting this out fixed the issue it is because an update to `pyflakes.checker` removed the attribute `Redefined` from the error `dict` defined by `FLAKE8_PYFLAKES_CODES`

# Refs

 - https://gitlab.com/pycqa/flake8/blob/master/src/flake8/plugins/pyflakes.py

**Comment by NotSqrt** [comment]
This is the pylint plugin, not pyflakes.
Have a look at https://github.com/SublimeLinter/SublimeLinter-pyflakes !

**Comment by flipdazed** [comment]
thanks :)
