### ISSUE TITLE
Linting with a global pylint fails because it outputs the help text

### ISSUE THREAD

**Issue by gerph** [SublimeLinter/SublimeLinter-pylint#47]
In the recent updates to SublimeLinter 4, my python code has stopped linting. In the console I get output such as:

```
SublimeLinter: #4 SublimeLinter.sublime-package:737: 'pylint' is linting 'AggregateTable.py'
INFO:SublimeLinter.lint.linter:'pylint' is linting 'AggregateTable.py'
SublimeLinter: #4 SublimeLinter.sublime-package:42: pylint: wanted python is 'None'
INFO:SublimeLinter.lint.base_linter.python_linter:pylint: wanted python is 'None'
SublimeLinter: #4 SublimeLinter.sublime-package:93: pylint: trying to use globally installed pylint
INFO:SublimeLinter.lint.base_linter.python_linter:pylint: trying to use globally installed pylint
SublimeLinter: #4 SublimeLinter.sublime-package:1159: Running ...

  Z:\projects\bits-python  (working dir)
  > C:\Python27\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n --init-hook=import sys;sys.path.append('');sys.path.append('c:\projects\longbacktrace\venv\Lib');sys.path.append('c:\projects\longbacktrace\venv\Lib\site-packages') --rcfile=pylintrc

INFO:SublimeLinter.lint.linter:Running ...

  Z:\projects\bits-python  (working dir)
  > C:\Python27\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n --init-hook=import sys;sys.path.append('');sys.path.append('c:\projects\longbacktrace\venv\Lib');sys.path.append('c:\projects\longbacktrace\venv\Lib\site-packages') --rcfile=pylintrc

SublimeLinter: #4 SublimeLinter.sublime-package:790: pylint output:
    Usage:  pylint [options] module_or_package
...
```

Which appears to be caused by the lack of the file-to-lint being included on the end of the command name.

A note inside SublimeLinter indicates that $file is no longer appended automatically:

https://github.com/SublimeLinter/SublimeLinter/blob/master/lint/linter.py#L1091

```
        if cmd == original_cmd and auto_append:
            logger.info(
                'Automatically appending the filename to cmd has been '
                'deprecated. Use $file, $temp_file or $file_on_disk instead.')
cmd.append(at_value)
```

which doesn't trigger as a log message because the `${args}` _is_ substituted into the command line, and thus they do not get appended.

My solution has been to make a small change to the 'linter.py' to append `${file}` to the end of the commands list, thus:

```
        return (
            'pylint',
            '--msg-template=\'{line}:{column}:{msg_id}: {msg} ({symbol})\'',
            '--module-rgx=.*',  # don't check the module name
            '--reports=n',      # remove tables
            '--persistent=n',   # don't save the old score (no sense for temp)
            '${args}',
            '${file}'
        )
```

This appears to have restored linting for me.

**Comment by kaste** [comment]
👌 Thanks for debugging this.

Clearly, the way forward is to just declare `$file` or whatever in the `cmd`. However, at `finalize_cmd` time `$args` already has been expanded. (Or it should.) So there must be something different that gets substituted. I've seen `sys.path.append('')` in your log. Is this intended or the missing piece here. (Something gets substituted with nothing.)

**Comment by kaste** [comment]
Maybe you can just implement `finalize_cmd` here for debugging

```
def finalize_cmd(self, *a, **kw):
	print(a, kw)
	return super().finalize_cmd(*a, **kw)
```

**Comment by gerph** [comment]
I assumed that the sys.path.append('') was putting the project path in there, but now I'm not sure.

Ah-ha... My paths configuration has:

```
            "paths": [
                "${directory}",
                "c:\\projects\\longbacktrace\\venv\\Lib",
                "c:\\projects\\longbacktrace\\venv\\Lib\\site-packages"
            ],
```

which I understood meant that it would substitute the project directory into the paths, but I guess it does not. I'll try to track down what that configuration should be to ensure that the current folder is included - although as this isn't substituting but I'm getting working linting, I guess the current folder must already be present anyhow!

**Comment by kaste** [comment]
I really hope you can dig into this bc I really tested this. E.g. from my console

```
SublimeLinter: #253 linter.py:1089: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.
SublimeLinter: #253 linter.py:1155: Running ...

  C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter  (working dir)
  > C:\Dev\python35\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n c:\users\c-flo\appdata\local\temp\tmpdyq43x.py

```

Here I don't have paths set, but in another project I have. Have you considered https://github.com/SublimeLinter/SublimeLinter-pylint/issues/47#issuecomment-386801247 for debugging.

**Comment by gerph** [comment]
I've just added that finalize_cmd to my code and I get quite a bit of output:

```
INFO:SublimeLinter.lint.base_linter.python_linter:pylint: trying to use globally installed pylint
(['C:\\Python27\\Scripts\\pylint.exe', "--msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})'", '--module-rgx=.*', '--reports=n', '--persistent=n', "--init-hook=import sys;sys.path.append('');sys.path.append('c:\\\\projects\\\\longbacktrace\\\\venv\\\\Lib');sys.path.append('c:\\\\projects\\\\longbacktrace\\\\venv\\\\Lib\\\\site-packages')", '--rcfile=pylintrc', '${file}'], ChainMap({'file_extension': '.py', 'file_name': 'AggregateTable.py', 'file_base_name': 'AggregateTable', 'folder': 'Z:\\projects\\bits-python', 'file_path': 'Z:\\projects\\bits-python', 'file_on_disk': 'Z:\\projects\\bits-python\\AggregateTable.py', 'file': 'Z:\\projects\\bits-python\\AggregateTable.py'}, {'file_name': 'AggregateTable.py', 'project_base_name': 'bits-python', 'file_path': 'Z:\\projects\\bits-python', 'file': 'Z:\\projects\\bits-python\\AggregateTable.py', 'project_name': 'bits-python.sublime-project', 'packages': 'C:\\Users\\Justin\\AppData\\Roaming\\Sublime Text 3\\Packages', 'project_extension': 'sublime-project', 'file_extension': 'py', 'platform': 'Windows', 'folder': 'Z:\\projects\\bits-python', 'file_base_name': 'AggregateTable', 'project': 'C:\\Users\\Justin\\SublimeText\\bits-python.sublime-project', 'project_path': 'C:\\Users\\Justin\\SublimeText'}, environ({'SYSTEMDRIVE': 'C:', 'MOZ_PLUGIN_PATH': 'C:\\Program Files (x86)\\Foxit PhantomPDF\\plugins\\', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'NUMBER_OF_PROCESSORS': '2', 'SVN_SSH': 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitPlink.exe', 'SESSIONNAME': 'Console', 'PUBLIC': 'C:\\Users\\Public', 'PROGRAMDATA': 'C:\\ProgramData', 'HOMEDRIVE': 'C:', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 55 Stepping 8, GenuineIntel', 'USERDOMAIN_ROAMINGPROFILE': 'CFERGUSON', 'LOGONSERVER': '\\\\CFERGUSON', 'TMP': 'C:\\Users\\Justin\\AppData\\Local\\Temp', 'ASL.LOG': 'Destination=file', 'GIT_SSH': 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitPlink.exe', 'FP_NO_HOST_CHECK': 'NO', 'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Python27\\;C:\\Python27\\Scripts\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Python35\\Scripts\\;C:\\Program Files\\Python35\\;C:\\Program Files (x86)\\Intel\\TXE Components\\TCS\\;C:\\Program Files\\Intel\\TXE Components\\TCS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Acer\\abFiles\\;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files\\Sublime Text 2\\;C:\\Program Files (x86)\\Beyond Compare 4\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\sourceforge\\ipmiutil\\;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files\\sourceforge\\ipmiutil\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\Git\\cmd;C:\\Users\\Justin\\bin', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'USERPROFILE': 'C:\\Users\\Justin', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'HOMEPATH': '\\Users\\Justin', 'WINDIR': 'C:\\Windows', 'USERDOMAIN': 'CFERGUSON', 'USERNAME': 'Justin', 'PROGRAMFILES': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'CFERGUSON', 'APPDATA': 'C:\\Users\\Justin\\AppData\\Roaming', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\Justin\\AppData\\Local\\Temp', 'PROCESSOR_REVISION': '3708', 'PROGRAMW6432': 'C:\\Program Files', 'PROCESSOR_LEVEL': '6', 'OS': 'Windows_NT', 'LOCALAPPDATA': 'C:\\Users\\Justin\\AppData\\Local', 'CLINK_DIR': 'C:\\Program Files (x86)\\clink\\0.4.8', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\'}))) {'at_value': 'Z:\\projects\\bits-python\\AggregateTable.py', 'auto_append': True}
```

**Comment by gerph** [comment]
If I remove both the ineffective "${directory}" from my sublimelinter pylint configuration, AND I remove the ${file} that I added to the end of the cmd generation, I get the help output again. Which I guess means that my assumption that ${directory} was the thing that affected the expansion was not right.

Full output at that point was:

```
SublimeLinter: #31 SublimeLinter.sublime-package:737: 'pylint' is linting 'AggregateTable.py'
INFO:SublimeLinter.lint.linter:'pylint' is linting 'AggregateTable.py'
SublimeLinter: #31 SublimeLinter.sublime-package:42: pylint: wanted python is 'None'
INFO:SublimeLinter.lint.base_linter.python_linter:pylint: wanted python is 'None'
SublimeLinter: #31 SublimeLinter.sublime-package:93: pylint: trying to use globally installed pylint
INFO:SublimeLinter.lint.base_linter.python_linter:pylint: trying to use globally installed pylint
(['C:\\Python27\\Scripts\\pylint.exe', "--msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})'", '--module-rgx=.*', '--reports=n', '--persistent=n', "--init-hook=import sys;sys.path.append('c:\\\\projects\\\\longbacktrace\\\\venv\\\\Lib');sys.path.append('c:\\\\projects\\\\longbacktrace\\\\venv\\\\Lib\\\\site-packages')", '--rcfile=pylintrc'], ChainMap({'file_extension': '.py', 'file_name': 'AggregateTable.py', 'file_base_name': 'AggregateTable', 'folder': 'Z:\\projects\\bits-python', 'file_path': 'Z:\\projects\\bits-python', 'file_on_disk': 'Z:\\projects\\bits-python\\AggregateTable.py', 'file': 'Z:\\projects\\bits-python\\AggregateTable.py'}, {'file_name': 'AggregateTable.py', 'project_base_name': 'bits-python', 'file_path': 'Z:\\projects\\bits-python', 'file': 'Z:\\projects\\bits-python\\AggregateTable.py', 'project_name': 'bits-python.sublime-project', 'packages': 'C:\\Users\\Justin\\AppData\\Roaming\\Sublime Text 3\\Packages', 'project_extension': 'sublime-project', 'file_extension': 'py', 'platform': 'Windows', 'folder': 'Z:\\projects\\bits-python', 'file_base_name': 'AggregateTable', 'project': 'C:\\Users\\Justin\\SublimeText\\bits-python.sublime-project', 'project_path': 'C:\\Users\\Justin\\SublimeText'}, environ({'SYSTEMDRIVE': 'C:', 'MOZ_PLUGIN_PATH': 'C:\\Program Files (x86)\\Foxit PhantomPDF\\plugins\\', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'NUMBER_OF_PROCESSORS': '2', 'SVN_SSH': 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitPlink.exe', 'SESSIONNAME': 'Console', 'PUBLIC': 'C:\\Users\\Public', 'PROGRAMDATA': 'C:\\ProgramData', 'HOMEDRIVE': 'C:', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 55 Stepping 8, GenuineIntel', 'USERDOMAIN_ROAMINGPROFILE': 'CFERGUSON', 'LOGONSERVER': '\\\\CFERGUSON', 'TMP': 'C:\\Users\\Justin\\AppData\\Local\\Temp', 'ASL.LOG': 'Destination=file', 'GIT_SSH': 'C:\\Program Files\\TortoiseGit\\bin\\TortoiseGitPlink.exe', 'FP_NO_HOST_CHECK': 'NO', 'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Python27\\;C:\\Python27\\Scripts\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Python35\\Scripts\\;C:\\Program Files\\Python35\\;C:\\Program Files (x86)\\Intel\\TXE Components\\TCS\\;C:\\Program Files\\Intel\\TXE Components\\TCS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Acer\\abFiles\\;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files\\Sublime Text 2\\;C:\\Program Files (x86)\\Beyond Compare 4\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\sourceforge\\ipmiutil\\;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\Calibre2\\;C:\\Program Files\\sourceforge\\ipmiutil\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\Git\\cmd;C:\\Users\\Justin\\bin', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'USERPROFILE': 'C:\\Users\\Justin', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'HOMEPATH': '\\Users\\Justin', 'WINDIR': 'C:\\Windows', 'USERDOMAIN': 'CFERGUSON', 'USERNAME': 'Justin', 'PROGRAMFILES': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'CFERGUSON', 'APPDATA': 'C:\\Users\\Justin\\AppData\\Roaming', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'C:\\Users\\Justin\\AppData\\Local\\Temp', 'PROCESSOR_REVISION': '3708', 'PROGRAMW6432': 'C:\\Program Files', 'PROCESSOR_LEVEL': '6', 'OS': 'Windows_NT', 'LOCALAPPDATA': 'C:\\Users\\Justin\\AppData\\Local', 'CLINK_DIR': 'C:\\Program Files (x86)\\clink\\0.4.8', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\'}))) {'at_value': 'Z:\\projects\\bits-python\\AggregateTable.py', 'auto_append': True}
SublimeLinter: #31 SublimeLinter.sublime-package:1159: Running ...

  Z:\projects\bits-python  (working dir)
  > C:\Python27\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n --init-hook=import sys;sys.path.append('c:\projects\longbacktrace\venv\Lib');sys.path.append('c:\projects\longbacktrace\venv\Lib\site-packages') --rcfile=pylintrc

INFO:SublimeLinter.lint.linter:Running ...

  Z:\projects\bits-python  (working dir)
  > C:\Python27\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n --init-hook=import sys;sys.path.append('c:\projects\longbacktrace\venv\Lib');sys.path.append('c:\projects\longbacktrace\venv\Lib\site-packages') --rcfile=pylintrc

SublimeLinter: #31 SublimeLinter.sublime-package:790: pylint output:
    Usage:  pylint [options] module_or_package

```

**Comment by kaste** [comment]
Ah, well we normalize `\\\\` to `\\`. So the culprit is that this plugin somehow double escapes when interpreting the paths setting. It does not compute the right import hook, I think.

**Comment by kaste** [comment]
So, I think #49 is the correct fix here. Can you try?

**Comment by gerph** [comment]
Definitely not correct - that means that the quoting doesn't happen on the strings, so you get a syntax error:

```
SublimeLinter: #55 pylint Extensions.py ERROR:
==============================================

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\pylint\__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 1148, in __init__
    'load-plugins': (self.cb_add_plugins, True),
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 1100, in preprocess_options
    cb(option, val)
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 1361, in cb_init_hook
    exec(value) # pylint: disable=exec-used
  File "<string>", line 1
    import sys;sys.path.append(c:\projects\longbacktrace\venv\Lib);sys.path.append(c:\projects\longbacktrace\venv\Lib\site-packages)
                                ^
SyntaxError: invalid syntax
```

**Comment by gerph** [comment]
That's quite ok - I was only saying to colleagues a few days ago "Until you've taken down a production system with a change you know was right and was had someone else review as right, you're just not trying hard enough :-)". I've made enough of my own, and I'll make more in the future, and so long as nobody gets hurt, all's happiness and light! :-)

**Comment by kaste** [comment]
Sorry, I can't replicate your failure now that I am actually on my computer.

Now, my change has 

```
"sys.path.append('{}')".format(path)
                 ^  ^
```

So there must be some quoting at least, which I don't see `sys.path.append(c:\projects\longbacktrace\venv\Lib)` in your traceback.

If I try, with these settings

```
     "pylint": {
         "disable": false,
         "paths": ["foo\\bar", "bar", "C:\\Dev\\GAE"],
```

(A bit fake, a bit real dirs)

it doesn't throw and shows 

```
SublimeLinter: #9 linter.py:1159: Running ...

  C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-pylint  (working dir)
  > C:\Dev\python35\Scripts\pylint.exe --msg-template='{line}:{column}:{msg_id}: {msg} ({symbol})' --module-rgx=.* --reports=n --persistent=n --init-hook=import sys;sys.path.append('foo\bar');sys.path.append('bar');sys.path.append('C:\Dev\GAE') C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-pylint\linter.py
```
